version: '3.8'

services:
  animes_hub:
    build: .
    container_name: animes_hub_web
    restart: always
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

  stremio-server:
    image: stremio/server:latest
    container_name: stremio_server
    restart: unless-stopped
    ports:
      - "11470:11470"
    environment:
      - NO_CORS=1
