// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB06LKHaJcqtg8fuwPe6GwB3Rqt4HxVE7k',
    appId: '1:134613216378:web:b32836fe66a12fedf71fc3',
    messagingSenderId: '134613216378',
    projectId: 'animeshub-f72f8',
    authDomain: 'animeshub-f72f8.firebaseapp.com',
    storageBucket: 'animeshub-f72f8.firebasestorage.app',
    measurementId: 'G-CTG46LWNPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOl1jIqzItsaZ7THu-d55wWY_NUviFIF0',
    appId: '1:134613216378:android:2b7ca8abd125814cf71fc3',
    messagingSenderId: '134613216378',
    projectId: 'animeshub-f72f8',
    storageBucket: 'animeshub-f72f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYVfdW3bA0yVw05jw-e7N19TxThY-0gA',
    appId: '1:134613216378:ios:1e52f74473cf59d7f71fc3',
    messagingSenderId: '134613216378',
    projectId: 'animeshub-f72f8',
    storageBucket: 'animeshub-f72f8.firebasestorage.app',
    iosBundleId: 'com.example.animesHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYVfdW3bA0yVw05jw-e7N19TxThY-0gA',
    appId: '1:134613216378:ios:1e52f74473cf59d7f71fc3',
    messagingSenderId: '134613216378',
    projectId: 'animeshub-f72f8',
    storageBucket: 'animeshub-f72f8.firebasestorage.app',
    iosBundleId: 'com.example.animesHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB06LKHaJcqtg8fuwPe6GwB3Rqt4HxVE7k',
    appId: '1:134613216378:web:f4eeddebbdab5bf5f71fc3',
    messagingSenderId: '134613216378',
    projectId: 'animeshub-f72f8',
    authDomain: 'animeshub-f72f8.firebaseapp.com',
    storageBucket: 'animeshub-f72f8.firebasestorage.app',
    measurementId: 'G-BXR4ZRLWK2',
  );
}
